### PR TITLE
Cowsay handling Emotes better

### PR DESCRIPTION
**Pull request by lcox74**
> This PR relates to Issue #85 

I was filled with joy and excitement after returning from camping, eager to check on my beloved `/cowsay` feature. But my joy quickly turned to despair when I received a devastating message: a bug had crept in, robbing users of the full experience and breaking their immersion with cow based communication. My heart shattered into a million pieces as I worked tirelessly to fix the issue, but to no avail. A sense of frustration and hopelessness washed over me as I encountered yet another bug.

Determined not to give up, I poured my heart and soul into finding the root cause of the problem. Hours turned into minutes as I persevered, and finally, I succeeded. `/cowsay` was restored to its former glory, and a new feature called `/cowthink` was added. The feeling of triumph that washed over me was indescribable, knowing that my hard work had paid off in the end. I was filled with a sense of pride and fulfillment, knowing that users could now interact with their beloved cows in new and exciting ways. 

Well until the PR gets pushed back with negative review. Anyway, fixed within this PR:

- [x] Emotes now should be replaced with `:{emote_name}:` instead of its ID
- [x] Words longer than `40 characters` will be broken up and wrapped as expected
- [x] The mytical `/cowthink` command has appeared, functioning the same `/cowsay` but visually different.

```
 ______ 
( Moo? )
 ------ 
   o 
    o 
        .--. 
       |o_o | 
       |:_/ | 
      //   \ \ 
     (|     | ) 
    /'\_   _/`\ 
    \___)=(___/ 
```

- [x] Strip white spaces from messages that cause funny results
- [x] Ignore code blocks that break the `\cowsay` art  
- [x] Added support for newline when `\n` is put in the message

### CODE REVIEW

**Comment by 49Indium** [comment]
This looks good to me, but I'll let someone with more experience double check.

**Comment by 49Indium** [comment]
Adding new lines brings forth a new issue with character counting. A message of say 495 lots of `\n` will be of length 990, so will pass the check in line 52. However, this will then produce 4*495 = 1980 characters in the body of the bubble alone. Adding on the characters of the cow, this leads to a message of over 200 messages which causes an error.

Otherwise, it looks good, but again, I'll wait for someone with more experience to double check.

**Comment by andrewj-brown** [comment]
Heya, just a heads-up that we have incoming changes [here](https://github.com/UQComputingSociety/uqcsbot-discord/pull/94) to our repo's code style that will be royal hell to merge into existing PRs. There's currently no ETA on us merging this; we want to give our extant PRs time to get merged beforehand.

If there's anything I can do to help get your PR merged (testing, reviews, etc) shoot me a ping on discord @</hax>#6701

**Comment by andrewj-brown** [comment]
LGTM, will merge later tonight if no-one else has complaints

**Pull request merged**
