### PR TITLE
Defer voteythumbs request (also prettified latex, and deferred xkcd)

### LINKED ISSUE #101: voteythumbs timeout (& general timeout) issues
The "voteythumbs" app command may take long enough to react with the three vote options that the interaction times out. This can cause commands that have executed successfully to return a "The application did not respond." message to the user, which is not ideal.

In terms of fixing this, interaction responses should be deferred before the reactions start, and then a proper followup response sent on command completion.

It would also be ideal if whoever takes on this issue did a wider review of interaction commands that may timeout (i.e. any web-requesting commands may timeout if the request takes too long) and properly defer them all to avoid false errors.

### PR DESCRIPTION
**Pull request by emadkhan713**
This PR should fix #101 somewhat.

However, some older commands should also be ported to the application-commands framework (`advent` (#68) and `holidays` come to mind), and subsequently deferred.

Also, this is my first OSS contribution, so I apologize if I've messed up in formatting / protocol for the PR.

### CODE REVIEW

**Comment by andrewj-brown** [comment]
`holidays` is fairly new; it looks like it doesn't have any app commands but that's because it actually has zero commands. It's just a cronjob that runs every day at 9am, generating the "Today is <thing> day!" message, so there's not really any need to "defer" a response per #101.

`advent` you're absolutely right about, it's a horrific monolith of a cog (and I'm saying this as the guy who wrote the starboard!) that probably should be completely stripped out and re-written. Especially considering we run giveaways, it's rather annoying that we don't have any way to easily link AoC participants to discord identities, nor opt-outs for the (many) alumni that have no desire to win.

**Comment by andrewj-brown** [comment]
As for this PR; lgtm and tested. If you could run black over the repo for code style (`poetry run black uqcsbot`) then I'd be happy to merge, although I'll leave it up just for a sec so others can chime in if they wish.

**Comment by emadkhan713** [comment]
ah right, I should've read a bit more into holidays then, soz.

and yeah, maybe I'll leave advent for later, might take a bit of a while to wrap my head around.

quick q: were xkcd or latex passing beforehand? because I didn't touch the parts that failed checks

**Comment by andrewj-brown** [comment]
On my machine (and on github) black wants to reformat `latex` and `xkcd`. It's just indentation changes; not an actual problem with your code logic, just formatting.

**Review by 49Indium — APPROVED** [review]
LGTM

**Review by 49Indium — APPROVED** [review]
Looks great. I'll give it some time for others to view, but can merge in soon.

**Comment by 49Indium** [comment]
Was very minor adjustments, which I think are due to our settings for black (a single line for `xkcd.py` and only a couple for `latex.py`). Running `poetry run black uqcsbot` was all I did.

**Comment by emadkhan713** [comment]
whoops! still learning the ropes, haha

**Review by andrewj-brown — APPROVED** [review]
lgtm and merging

**Pull request merged**
