### PR TITLE
Update to Python 3.10

### PR DESCRIPTION
**Pull request by JamesDearlove**
Something something we merged a commit that had code that requires 3.10, we didn't realise, the bot crashed. This makes the bot run on 3.10

### CODE REVIEW

**Comment by lcox74** [comment]
What can possibly go wrong, versioning has never caused a problem ™

**Review by LimaoC — APPROVED** [review]
> we merged a commit that had code that requires 3.10

Huh, I wonder who would've made a silly mistake like that

**Comment by JamesDearlove** [comment]
Dunno

**Comment by andrewj-brown** [comment]
> we
🤔

**Comment by JamesDearlove** [comment]
it's a team effort 🥰

**Pull request merged**
