### PR TITLE
SECaT slash command and course statistics

### PR DESCRIPTION
**Pull request by Jake-Moss**
This is the accompanying PR to #180. I've just finished my exams and thought I'd follow up on the scrapper and get it into a working and shareable shape.

Current state:
- [X] Basic functionality (return responses)
image
- [X] Cache various `viewstates` and `eventargs`
- [X] Cache SECaT responses
- [X] Basic result display
image
- [ ] Basic Discord integration
- [ ] Embeds and interactive buttons
- [ ] Autocomplete
- [ ] Database storage? Everything is currently in memory only
- [ ] Tests

### CODE REVIEW

**Comment by Jake-Moss** [comment]
For displaying results, I'm not entirely sure what would be best. I've tried to mimic the original display with matplotlib to produce something, but its not great. For a text response, it's very easy to create a pivot table but that's not the most readable, and formatting those decimals requires `JinJa2` apparently.
```
ANSWER                           1 Strongly Agree    2 Agree  3 Neither Agree/Disagree  4 Disagree  5 Strongly Disagree
QUESTION_NAME                                                                                                          
Q1: Understand Aims & Goals             17.857143  37.500000                 23.214286   16.071429             5.357143
Q2: Intellectually Stimulating          16.363636  45.454545                 10.909091   16.363636            10.909091
Q3: Well Structured                      9.090909  25.454545                 27.272727   21.818182            16.363636
Q4: Learning Materials Assisted         10.909091  40.000000                 25.454545   16.363636             7.272727
Q5: Assessment Reqs Clear                7.142857  30.357143                 16.071429   21.428571            25.000000
Q6: Received Helpful Feedback           11.111111  27.777778                 24.074074   24.074074            12.962963
Q7: Learned a lot                       18.181818  38.181818                 23.636364    9.090909            10.909091
Q8: Overall Rating                      12.500000  19.642857                 19.642857   28.571429            19.642857
```
I think some sort of chart display is essential, but I'm not sure if that should be a single question response, or all 8 or something in-between.

UX wise my current thoughts for slash commands are:
- Full secat response
- Summary statistics, enrolment +  response rate, overall rating
- Smaller responses for specific questions
All with semester or latest specifiers.

Currently everything is on-demand as I've have a discord single slash command only use-case in mind, but it would be possible to scrap the entirety of it uqfinal-style. With proper database integration this would let us create rankings for courses and generally see distribution of the previous years over the courses and track changes over time. I'm not sure how much data there would be as responses are ~1MB and we would need one for every course, for every semester. Not huge, but also not nothing.

**Comment by andrewj-brown** [comment]
Well, unfortunately, I have bad news. I reached out to PBI to see if there were any best-practices we should be engaging in with this project (`User-Agent` requirements, for example), and got a response back from ITALI, that SeCaT data will stop being publicly available in Feb next year.

Saving the data as-is and providing graphs based on old data is out-of-the-question too, as it'll only get older and older, and I don't think we should be hosting data that UQ itself has made private.

A real shame, this project would have been really cool.

**Comment by andrewj-brown** [comment]
Well, unfortunately, I have bad news. I reached out to PBI to see if there were any best-practices we should be engaging in with this project (`User-Agent` requirements, for example), and got a response back from ITALI, that SeCaT data will stop being publicly available in Feb next year.

Saving the data as-is and providing graphs based on old data is out-of-the-question too, as it'll only get older and older, and I don't think we should be hosting data that UQ itself has made private.

A real shame, this project would have been really cool.

**Comment by Jake-Moss** [comment]
Aw damn, that's shame to hear. Considering the scrapper itself it fully functional I might archive the data for my own purposes over the holidays, might get a couple cool graphs out of it, but I agree with regards to re-hosting it.

Interesting that they're making it private, I'm sure many people find it a useful tool to evaluate courses, I certainly do.

**Pull request closed without merging**
