### PR TITLE
Removed The Disciplinary Function

### PR DESCRIPTION
**Pull request by ThatSealgair**
Please accept I promise I am a changed man.

### CODE REVIEW

**Review by JamesDearlove — CHANGES_REQUESTED** [review]
Requesting changes of yourself before this can be approved 🥰

**Comment by q-horton** [comment]
lgtm

**Comment by ThatSealgair** [comment]
Pls sir

**Comment by LimaoC** [comment]
Released on parole.

**Comment by ThatSealgair** [comment]
[Thank you](https://media.tenor.com/l1DiQH7v0AIAAAAC/the-grinch-evil-smile.gif)

**Pull request merged**
