### PR TITLE
Fixed bug where workingon calls the same person twice

### PR DESCRIPTION
**Pull request by 49Indium**
The daily "Tell us about something cool you are working on!" message calls on two people, but could call on the same person twice (as seen [here](https://discord.com/channels/813324385179271168/813325735620116490/1119884203241259128)). This should hopefully stop this rare bug from happening.

### CODE REVIEW

**Comment by andrewj-brown** [comment]
lgtm, but only if we're sure it's a bug worth fixing - there's a 1/1444 chance and shrinking, and it gives us something to talk about in the (extremely usual) case that the actual requestee doesn't respond.

**Comment by 49Indium** [comment]
Fair enough. I'll let others chime in.

(Re revert: Oops, pushed to wrong branch)

**Comment by lcox74** [comment]
Lgtm. But you're removing character from the bot

**Comment by bradleysigma** [comment]
Yeah, with 1444 members (and counting), you'd expect to go four years between double pings. The change I'd prefer is bumping it up to three pings every day.

**Pull request closed without merging**
