### PR TITLE
Spoilering xkcd Description

### PR DESCRIPTION
**Pull request by ew-b**
Don't let the channel branch name fool you, this has nothing to do with logs and everything to do with not spoilering the plot. How do we do that? F strings and four little bars, that's it, discord does the rest with its spoiler function.

### CODE REVIEW

**Review by 49Indium — APPROVED** [review]
Looks good to me

**Comment by lcox74** [comment]
I feel this damages the character of xkcd

**Comment by lcox74** [comment]
I've been told to let it go. Lgtm

**Comment by andrewj-brown** [comment]
doinked

**Pull request merged**
