### PR TITLE
Create Cato funciton 

### PR DESCRIPTION
**Pull request by bradleysigma**

### CODE REVIEW

**Comment by LimaoC** [comment]
Mm... I'm not sure I should comment on this due to a potential conflict of interest.

**Comment by JamesDearlove** [comment]
You're not getting out of this that easily

**Comment by JamesDearlove** [comment]
Once again requesting @RachelChiong to review this

**Comment by q-horton** [comment]
lgtm

**Comment by RachelChiong** [comment]
_sigh_

**Pull request closed without merging**
